senzing-garage/sdk-components-ng

- examples/search-with-prefs/src/app/app.component.html
- examples/search-with-prefs/src/app/app.component.ts
- package-lock.json
- src/lib/configuration/sz-preferences/sz-preferences.component.html
- src/lib/configuration/sz-preferences/sz-preferences.component.ts
- src/lib/models/entity-search.ts
- src/lib/models/folio.ts
- src/lib/sdk.module.ts
- src/lib/search/sz-search/sz-search.component.html
- src/lib/search/sz-search/sz-search.component.ts
- src/lib/services/sz-folios.service.ts
- src/lib/services/sz-prefs.service.ts
- src/lib/services/sz-search.service.ts
- src/public_api.ts
#109 
This is a feature for saving the last X searches in memory. The previous unique values typed in(up to the max specified in prefs) will be available via type-ahead suggestion or pulldown from the specific input box. Right now selecting a previous value just fills out the individual field, however it is possible to perform a more robust action on select. This is what I have done specifically in just the name field, when selecting a previously searched for name from the name drop-down, the name AND any other parameters present when that search was performed are auto-filled. This was only implemented in the name field because it would open up a lot of complexity checking which values should be filled over other ones etc but I think it is worth further discussion about the right way to …
> Type-Ahead and "remember last X" searches

- src/lib/models/folio.ts
- src/lib/services/sz-folios.service.ts
Search History was doing all sorts of **"Odd"** things. This catches **most**(_if not all_) of the edge-cases in logic. #123 
* prevents adding duplicate history entries
* SzFoliosService re-wired to use prefs reference indirectly by referencing local getter. This way there is no need to "sync" the shallow reference items.
* SzFoliosService will attempt to create prefs searchForm history folio if not set properly or previously initialized.
> Search History fixes

- src/lib/configuration/sz-preferences/sz-preferences.component.html
- src/lib/configuration/sz-preferences/sz-preferences.component.scss
- src/lib/configuration/sz-preferences/sz-preferences.component.spec.ts
- src/lib/search/sz-search/sz-search.component.html
- src/lib/search/sz-search/sz-search.component.ts
- src/lib/services/sz-prefs.service.ts
- added pref to enable/disable search history feature. 
- combined "form" and "results" prefs in to single column to save space.
Issue number: #125
> pref for disabling search history #125

- src/lib/models/folio.ts
when user searches for something that was already in search history the item is moved to top of stack chronologically.
Issue number: #126
> pre-existing search terms get moved to top of stack. #126

- src/lib/services/sz-bulk-data.service.ts
Issue number: #150 
change the ds mapping key from `null` to `""` for rows with no ds provided.
change the ds entity key from `null` to `""` for rows with no entity type provided.
resolves #150
resolves https://github.com/Senzing/entity-search-web-app/issues/123
> #150 fix for CSV bulk load issue

- src/lib/entity/detail/sz-entity-detail-graph/sz-entity-detail-graph-filter.component.html
- src/lib/entity/detail/sz-entity-detail-graph/sz-entity-detail-graph-filter.component.scss
- src/lib/entity/detail/sz-entity-detail-graph/sz-entity-detail-graph-filter.component.ts
- src/lib/entity/detail/sz-entity-detail-graph/sz-standalone-graph.component.ts
resolves #162
color picker was acting weird in Firefox.. also there was a scenario where datasource colors were never being applied to primary nodes(ie, nodes in the initial search result). Also, when "active/focused" entity color is selected it will override any per-datasource color(s) that may normally apply to those nodes. I added a * **note** in there about that for now, the real fix is probably to do a custom control list(like drag to reorder, unselect etc)
> #162 fix for FF color picker being weird

- src/lib/common/utils.ts
- src/lib/entity/detail/sz-entity-detail-graph/sz-entity-detail-graph-filter.component.html
- src/lib/entity/detail/sz-entity-detail-graph/sz-entity-detail-graph-filter.component.scss
- src/lib/entity/detail/sz-entity-detail-graph/sz-entity-detail-graph-filter.component.ts
- src/lib/entity/detail/sz-entity-detail-graph/sz-entity-detail-graph.component.ts
- src/lib/entity/detail/sz-entity-detail-graph/sz-standalone-graph.component.ts
- src/lib/models/data-sources.ts
- src/lib/sdk.material.module.ts
- src/lib/services/sz-prefs.service.ts
- src/public-api.ts
resolves #111 
When an entity belongs to multiple datasources the entities color would always be the last color assigned to a datasource that it belonged to.
The datasource color precendent/order can be dragged to reorder(when using the filter control). Datasource colors are stored in *SzDataSourceComposite[]* whose models now include a name/color/index value.
https://user-images.githubusercontent.com/13721038/117600101-2a233980-b100-11eb-8f4d-ba19bdb6f642.mp4
> Issue111.awinters.1

- package-lock.json
- package.json
- sdk-components-web/package.json
- src/lib/configuration/sz-configuration/sz-configuration.component.ts
- src/lib/configuration/sz-preferences/sz-preferences.component.ts
- src/lib/entity/detail/sz-entity-detail-graph/sz-entity-detail-graph-control.component.ts
- src/lib/entity/detail/sz-entity-detail-graph/sz-entity-detail-graph-filter.component.ts
- src/lib/entity/detail/sz-entity-detail-graph/sz-entity-detail-graph.component.ts
- src/lib/entity/detail/sz-entity-detail-graph/sz-standalone-graph.component.ts
- src/lib/entity/detail/sz-entity-details-section/collapsible-card.component.ts
- src/lib/entity/detail/sz-entity-details-section/header.component.ts
- src/lib/entity/detail/sz-entity-details-section/sz-entity-details-section.component.ts
- src/lib/entity/sz-entity-match-pill/sz-entity-match-pill.component.ts
- src/lib/entity/sz-entity-record-card/sz-entity-record-card-content/sz-entity-record-card-content.component.ts
- src/lib/entity/sz-entity-record-card/sz-entity-record-card-header/sz-entity-record-card-header.component.ts
- src/lib/models/folio.ts
- src/lib/models/responces/search-results/raw-data.ts
- src/lib/models/responces/search-results/sz-search-result-entity-data.ts
- src/lib/record/sz-entity-record-viewer.component.ts
- src/lib/search/sz-search-result-card/sz-search-result-card-content/sz-search-result-card-content.component.ts
- src/lib/services/sz-admin.service.ts
- src/lib/services/sz-configuration.service.ts
- src/lib/services/sz-entitytypes.service.ts
- src/lib/services/sz-pdf-util.service.ts
- src/lib/services/sz-prefs.service.ts
- src/lib/services/sz-search.service.ts
- src/package.json
related #219
To facilitate the _option_ for implementations to pass additional HTTP headers to API Server endpoints.
Passing additional or custom headers are necessary in certain operation scenario's, ie: passing `X-Amz-Security-Token` to a [Cognito](https://aws.amazon.com/cognito/) enabled [API Gateway](https://aws.amazon.com/api-gateway/) address after user authentication.
- Methods added to SzConfigurationService :
- addHeaderToApiRequests
- removeHeaderFromApiRequests
- Accessors added to SzConfigurationService :
- additionalApiRequestHeaders
- @Input() Accessor added to SzConfigurationComponent : 
- additionalHeaders
- Code Cleanup (various commented out or unused variables removed)
- Bugfix for #111 (found while checking integration)
> Issue219.awinters.2

- CHANGELOG.md
- examples/search-in-graph/src/app/app.component.html
- package-lock.json
- package.json
- src/lib/common/utils.ts
- src/lib/graph/sz-graph-filter.component.html
- src/lib/graph/sz-graph-filter.component.scss
- src/lib/graph/sz-graph-filter.component.ts
- src/lib/graph/sz-graph.component.html
- src/lib/graph/sz-graph.component.ts
- src/lib/models/graph.ts
- src/lib/sdk.material.module.ts
- src/lib/services/sz-prefs.service.ts
resolves #283 
To support *Filter By Match Key Tokens* functionality.
The graph filters found in the `SzStandaloneGraphComponent` can now show a tag cloud of *Match Key Tokens*. If setting the `showMatchKeyTokenFilters="true"` you should also set the `showMatchKeyFilters]="false"` since the two options are exclusive and will interfere with proper function of the other.
> Match Key Token Graph Filtering

- angular.json
- examples/search-in-graph/src/app/app.component.html
- examples/search-with-results-and-details/src/app/app.component.html
- package-lock.json
- package.json
- src/lib/graph/sz-graph-filter.component.html
- src/lib/graph/sz-graph-filter.component.scss
- src/lib/graph/sz-graph-filter.component.ts
- src/lib/graph/sz-graph.component.html
- src/lib/graph/sz-graph.component.ts
- src/lib/models/graph.ts
- src/lib/scss/styles.scss
- src/lib/scss/theme.scss
- src/lib/services/sz-prefs.service.ts
- src/package.json
resolves #291 
There was an ask from @jbutcher21 for the Match Key Token filter(s) to only apply to the first-level deep relationships. He thought it was confusing that there match keys being show in the filter(s) list that were only present between entity nodes who'm themselves were related to the focal entity by a different match key(s).
I'm not **100%** sure this is the _optimal_ solution, I _think_ what we probably **_should do_** is list the primary tags **_WITH_** the option to expand the list to include the other non-primary related tags for more capable filtering when needed(we definitely will need it when I merge in edge expansion). probably using a `...` and/or a different tag chip color etc but I need a little more time to work that out. This solution will get the job done for …
> #291 add option to limit scope of match key tokens to just primary rels

- src/lib/entity/detail/sz-entity-detail.component.ts
- src/lib/scss/styles.scss
- src/lib/search/sz-search-results/sz-search-results.component.ts
- src/lib/why/sz-why-entities-dialog.component.html
- src/lib/why/sz-why-entities-dialog.component.scss
- src/lib/why/sz-why-entities.component.ts
- src/lib/why/sz-why-entity-dialog.component.html
- src/lib/why/sz-why-entity-dialog.component.scss
- src/lib/why/sz-why-entity.component.ts
resolves #302 
There was a **80% maximum** view width resize restriction set on the **_Why / Why Not_** modals. Some users reported that it was inconvenient. 
- 80% width restriction removed
- Double click to toggle between 100vw/100vh and unset view width and height
> #302 dblclick min/max why/whynot modal titlebar. 80vw restriction removed

- src/public-api.ts
resolves #313
Some models/objects **_WERE_** being exposed by `@senzing/sdk-graph-components` that now should be exposed by `@senzing/sdk-components-ng` since we relocated the graph components to this repository. Consuming applications that were referencing these models/objects would have no alternative/comparable type's to import otherwise. The following models are now exposed:
- [SzSearchResultEntityData](https://github.com/Senzing/sdk-components-ng/blob/main/src/lib/models/responces/search-results/sz-search-result-entity-data.ts) 
- [SzNetworkGraphInputs](https://github.com/Senzing/sdk-components-ng/blob/main/src/lib/models/graph.ts)
- [SzMatchKeyComposite](https://github.com/Senzing/sdk-components-ng/blob/main/src/lib/models/graph.ts)
- …
> #313 export missing models/interfaces

- src/lib/graph/sz-relationship-network/sz-relationship-network.component.ts
resolves #311 
So that if/when there are multiple **_CORE_** nodes they do not initially overlap.
graph positioning usability
> give primary nodes unique initial x,y positions

- CHANGELOG.md
- examples/search-in-graph/src/app/app.component.html
- examples/search-in-graph/src/app/app.component.scss
- examples/search-in-graph/src/app/app.component.ts
- package.json
- src/lib/entity/detail/sz-entity-detail-graph/sz-entity-detail-graph.component.ts
- src/lib/entity/detail/sz-entity-detail-graph/sz-standalone-graph.component.html
- src/lib/entity/detail/sz-entity-detail-graph/sz-standalone-graph.component.ts
- src/lib/graph/sz-graph-filter.component.html
- src/lib/graph/sz-graph-filter.component.scss
- src/lib/graph/sz-graph-filter.component.ts
- src/lib/graph/sz-graph.component.html
- src/lib/graph/sz-graph.component.ts
- src/lib/graph/sz-relationship-network/sz-relationship-network.component.ts
- src/lib/scss/theme.scss
- src/lib/sdk.material.module.ts
- src/lib/services/sz-prefs.service.ts
- src/lib/services/sz-search.service.ts
- src/package.json
resolves #347 
resolves #350 
resolves #355 
- the following event emitters added to `SzGraphFilterComponent`
- `matchKeyTokenSelectionScopeChanged` when the user switches from `CORE` to `EXTRANEOUS` match key token scope
- the following getters and setters added to `SzGraphFilterComponent`
-  `maxEntitiesLimit` the maximum value that the slider control will allow. default is 200.
-  `unlimitedMaxEntities` ignore the `maxEntities` value and always pull up to 40000
-  `unlimitedMaxScope` ignore the `buildOut` value and always pull up to 10
- the following getters and setters added to `SzGraphComponent`
- `unlimitedMaxEntities`
- `unlimitedMaxScope`
- `maxEntitiesFilterLimit`
- the following event emitters on `SzGraphComponent`
- `renderStarted` not sure why this didn't exist since …
> Graph Filtering bugfixes and additions

- CHANGELOG.md
- src/lib/graph/sz-graph.component.ts
- src/lib/graph/sz-relationship-network/sz-relationship-network.component.ts
resolves #358 
the match key filtering for core relationships was incorrect. it was essentially counting match keys from non-primary relationships between two entities that ARE related to the primary entity.. which is not correct. 
fixes faulty match key filtering
> #358 fix for core rel match key filtering

- .github/dependabot.yml
if this doesn't include security related updates(those are treated separately though the UI) there is no need to check these daily.
> dependabot finetuning

- CHANGELOG.md
- package.json
- src/lib/graph/sz-relationship-network/sz-relationship-network.component.scss
- src/lib/graph/sz-relationship-network/sz-relationship-network.component.ts
- src/lib/scss/graph.scss
- src/lib/scss/styles.scss
- src/lib/scss/theme.scss
- src/package.json
resolves #308
resolves #383 
- match keys displayed were incorrect
- match keys were hard to read.
- link match key label readability
- link match key label accuracy
> match keys on graph relationship links fixes

- .github/dependabot.yml
- CHANGELOG.md
- package-lock.json
- package.json
- src/lib/common/utils.ts
- src/lib/configuration/sz-preferences/sz-preferences.component.spec.ts
- src/lib/configuration/sz-preferences/sz-preferences.component.ts
- src/lib/entity/detail/sz-entity-detail-graph/sz-entity-detail-graph.component.html
- src/lib/entity/detail/sz-entity-detail-graph/sz-standalone-graph.component.html
- src/lib/entity/detail/sz-entity-detail.component.html
- src/lib/entity/detail/sz-entity-detail.component.ts
- src/lib/graph/sz-graph-filter.component.html
- src/lib/graph/sz-graph-filter.component.scss
- src/lib/graph/sz-graph-filter.component.ts
- src/lib/graph/sz-graph.component.html
- src/lib/graph/sz-graph.component.ts
- src/lib/graph/sz-relationship-network/sz-relationship-network.component.scss
- src/lib/graph/sz-relationship-network/sz-relationship-network.component.ts
- src/lib/scss/graph.scss
- src/lib/scss/theme.scss
- src/lib/services/sz-prefs.service.spec.ts
- src/lib/services/sz-prefs.service.ts
- src/lib/why/sz-why-entities.component.ts
- src/package.json
resolves #407 
resolves #413 
resolves #414 
resolves #415 
resolves #417 
#407 changes the graph network calls to a composite pattern to better handle entities with large amounts of relationships. Initial testing for an entity with >1k related entities went from 45s before render to 12s.
- Added "hide indirect links" UI control to graph filtering component.
- Added `suppressL1InterLinks` to graph preferences
- Added `linkColor` to graph preferences
- Added `indirectLinkColor` to graph preferences
- Added *Link Color* section to graph filter component
- Added *Data Sources* list to graph hover tooltip
- `showMatchKeys` UI/UX parameter renamed to `showLinkLabels` to avoid confusion with `matchKeyFilters` and `showMatchKeyTokens` which are functional/behavior parameters.
- Graph api call …
> Graph component optimizations and bugfixes

- CHANGELOG.md
- examples/search-in-graph/src/app/app.component.html
- examples/search-in-graph/src/app/app.component.ts
- src/lib/entity/detail/sz-entity-detail-graph/sz-entity-detail-graph.component.ts
- src/lib/entity/detail/sz-entity-detail-graph/sz-standalone-graph.component.ts
- src/lib/graph/sz-graph-filter.component.ts
- src/lib/graph/sz-graph.component.ts
- src/lib/graph/sz-relationship-network/sz-relationship-network.component.ts
- src/lib/scss/graph.scss
- src/lib/sdk.module.ts
- src/lib/services/sz-css-class.service.ts
- src/lib/services/sz-prefs.service.ts
resolves #416 
when a user would change a parameter or a method was called internally that caused a re-paint sometimes color information that was applied to each graph node programatically was lost if the appropriate color subroutine was not called during or after the other method call. using this new methodology no color information is stored on the nodes themselves, the node(s) are tagged with css class names that represent a attribute that can be colored, then a css class that matches that selector is injected in to the head of the document. no subsequent repaint's are necessary and selecting and crawling all the graph nodes to assign color information is no longer necessary(which may have a minor perf benefit)
performance and method of how we "color" specific elements in the graph …
> #416 new way to do user defined graph node colors

- CHANGELOG.md
- src/lib/entity/detail/sz-entity-detail.component.html
- src/lib/entity/detail/sz-entity-detail.component.ts
- src/lib/entity/detail/sz-entity-details-section/collapsible-card.component.html
- src/lib/entity/detail/sz-entity-details-section/collapsible-card.component.ts
- src/lib/entity/detail/sz-entity-details-section/sz-entity-details-section.component.html
- src/lib/entity/detail/sz-entity-details-section/sz-entity-details-section.component.ts
- src/lib/entity/sz-entity-record-card/sz-entity-record-card-content/sz-entity-record-card-content.component.html
- src/lib/entity/sz-entity-record-card/sz-entity-record-card-content/sz-entity-record-card-content.component.ts
- src/lib/models/data-source-record-selection.ts
resolves #439 
we wanted to expose the "why not" report through the UI in the entity detail component.
users can now click on the "why not" button in the "possible matches" section of the detail component to show a report comparing why the current entity and the related entity did not resolve to a single unified entity.
> #439 why not added to possible matches

- src/lib/entity/detail/sz-entity-detail-graph/sz-standalone-graph.component.ts
- src/lib/entity/detail/sz-entity-detail-header/header.component.ts
- src/lib/entity/detail/sz-entity-detail.component.ts
- src/lib/graph/sz-graph-filter.component.html
- src/lib/graph/sz-graph-filter.component.scss
- src/lib/graph/sz-graph-filter.component.ts
- src/lib/scss/styles.scss
- src/lib/scss/theme.scss
- src/lib/sdk.material.module.ts
- src/lib/search/sz-search-results/sz-search-results.component.ts
- src/lib/search/sz-search/sz-search-identifiers-picker.component.scss
- src/lib/search/sz-search/sz-search-identifiers-picker.component.ts
- src/lib/search/sz-search/sz-search.component.ts
- src/lib/shared/alert-dialog/sz-alert-dialog.component.scss
- src/lib/shared/alert-dialog/sz-alert-dialog.component.ts
- src/lib/shared/multi-select-button/multi-select-button.component.scss
- src/lib/why/sz-why-entities-dialog.component.scss
- src/lib/why/sz-why-entities.component.scss
- src/lib/why/sz-why-entities.component.ts
- src/lib/why/sz-why-entity-dialog.component.scss
- src/lib/why/sz-why-entity.component.scss
- src/lib/why/sz-why-entity.component.ts
As part of the angular@15 updates the material modules/components made some structural changes that invalidated some of the styling overrides we were using. This brings those components up to date with new selectors/styles.
> updates to angular material@15 syntax/modules

- src/lib/entity/sz-entity-record-card/sz-entity-record-card-content/sz-entity-record-card-content.component.ts
- src/lib/graph/sz-graph-filter.component.spec.ts
- src/lib/graph/sz-graph.component.ts
- src/lib/services/sz-prefs.service.ts
resolves #496 
turn match keys in graph _on_ by default
> #496 match keys turned on by default

- src/lib/graph/sz-graph.component.ts
- src/lib/graph/sz-relationship-network/sz-relationship-network.component.ts
- src/lib/scss/graph.scss
- src/lib/scss/theme.scss
resolves #499 
We had changed the api call to improve graph performance which limits the number of fields that are pulled back in the request. The fields that we **_were_** using for detecting whether an entity should display as a company or a person icon are no longer being returned. 
graph icons are now non-specific until we add a new datapoint that can be used for detection in the api@4.x release.
While I was changing the icon I made it so that criteria/datasource coloring of nodes would apply more intelligently to spaces _INSIDE_ the icon(rather than just changing the whole fill color like on the old ones).
> #499 new graph icons/better node coloring

- src/lib/sdk.module.ts
- src/lib/services/sz-config-data.service.ts
- src/lib/why/sz-why-entities.component.ts
- src/lib/why/sz-why-entity.component.ts
- src/lib/why/sz-why-report-base.component.ts
resolves #525 
the how/why/why not components wouldn't finish loading when the server doesn't respond back with the active config. 
when the server doesn't respond back with the fTypes the components just ignore trying to sort the field rows by the config order and instead render in the order as provided in the api why/how response features.
> bugfix for how/why/why not

- src/lib/entity/detail/sz-entity-detail-header/header.component.html
- src/lib/entity/detail/sz-entity-detail-header/header.component.ts
- src/lib/entity/detail/sz-entity-detail.component.html
- src/lib/entity/detail/sz-entity-detail.component.ts
- src/lib/how/cards/sz-how-virtual-entity-card.component.html
- src/lib/scss/styles.scss
- src/lib/shared/alert-dialog/sz-alert-dialog.component.html
resolves #538 
The how button would be displayed regardless of whether or not an entity's how report would be empty due to single record entities or `EXACT_MATCH` records leading to users being given empty or broken looking reports.
- `dynamicHowFeatures` when enabled will make a background request to the how api surface when the detail component is loaded to selectively either enable warning messages or disable/enable **"How"** buttons
- `howFunctionDisabled` will return true if the how related components have been disabled
- `showHowFunctionWarnings`  when set to true will display a warning message when a user clicks a **"How"** button and the associated how report would be blank .
- `howReportUnavailable` will be emitted when the preflight request that is performed does not return any …
> #538 options for pre-flighting the How Report

- src/lib/how/sz-how-step-stack.component.scss
resolves #545 
how cards that were members of a stack with more than  10 members would not show up
bugfix
> #545 fix for how card stacking issue

- src/lib/how/cards/sz-how-card-base.component.ts
- src/lib/services/sz-how-ui.service.ts
resolves #572 
ADD RECORD stacks were opening by default when user expanded parent element
> #572 stacks closed by default

- src/lib/how/sz-how-entity.component.ts
- src/lib/services/sz-how-ui.service.ts
resolves #574 
when a how result had multiple final states and a second state has only a single "CREATE" step(both records singletons) there was a gap in logic resulting in an step being displayed with no parent "FINAL" step.
> #574 fix for edgecase multiple final states single step

- src/lib/why/sz-why-entities.component.ts
- src/lib/why/sz-why-report-base.component.ts
resolves #686 
currently not all features in the why/why not screen display scores if they're in the match key. Often, especially in the case of Why Not we want to display low-ranking scores even if they are not in the match key because they inform the user what may be contributing to the non-matching behavior, or why two results may have not resolved.
> #686 include low-scoring features

- src/lib/common/utils.ts
- src/lib/graph/sz-graph-filter.component.html
- src/lib/graph/sz-graph-filter.component.ts
- src/lib/graph/sz-graph.component.ts
- src/lib/graph/sz-relationship-network/sz-relationship-network.component.ts
- src/lib/scss/graph.scss
- src/lib/services/sz-css-class.service.ts
resolves #689
resolves #690
When selecting datasource colors if the primary node color is chosen and the primary node is part of that datasource the color displayed is the color chosen for the primary and not the datasource member color.
Additionally a critical bug was found while working on this issue that causes an infinite re-render loop. This PR includes the fix for that issue as well( #689 )
 
Changing this behavior will allow the primary focused node's color to be changed to the color of it's datasource if a color has been chosen. Additionally there is a new behavior to UNSET the chosen color be selecting either pure white(#ffffff) or pure black(#000000) in the color picker. Being able to unset a chosen color for a datasource that the primary node is a member off will return it's …
> #690 #689 graph node coloring changes

- package.json
- src/lib/configuration/sz-preferences/sz-preferences.component.spec.ts
- src/lib/graph/sz-relationship-network/sz-relationship-network.component.ts
- src/lib/services/sz-prefs.service.spec.ts
- src/lib/services/sz-prefs.service.ts
resolves #739 
graph would get stuck in render loop on second request when component not destroyed.
> #739 fixes for graph render loop

- .github/workflows/add-labels-standardized.yaml
- .github/workflows/add-to-project-app-server-dependabot.yaml
- .github/workflows/add-to-project-app-server.yaml
- .github/workflows/npm-build.yaml
Issue number: senzing-factory/build-resources#179
> senzing-factory/build-resources#179 add slack notifications
