- .gitignore
- README.md
Please review the README.md changes.  I tried to factor out the stuff related to the Senzing REST API Server and reference the existing stuff.
I also removed as much HTML as I could (leaving the table) so as to get the linter to not complain.
Other minor changes included:
- Changing "rest-api-server-java" to "Senzing-api-server" (something you Ara already did on the other branch)
- Adding the registered trademark symbol next to the first occurrence of "Senzing" and capitalizing Senzing per the email on using trademarks properly
- Referenced the "Senzing Rest API" spec directly as well
- Changed <B> and </B> tags to double asterisks for markdown
- Added spacing, removed spacing, added line breaks and removed blank lines per the linter
> Modified .gitignore and updated README.md

- .travis.yml
- README.md
- package-lock.json
removed e2e from .travis.yml to see if it resolves issue.
updated readme with new build image ref, and docs location.
> removing e2e temporarily #98

- README.md
- src/README.md
- src/lib/search/sz-search-results/sz-search-results.component.ts
* fixed premature change detection in searchResults component on pref change. (#100)
* added npm package version badges to readme (_see below_)
* updated npm package readme
> Issue100.awinters.1

- docs/components/SzPreferencesComponent.html
- docs/index.html
- src/README.md
- src/lib/configuration/sz-preferences/sz-preferences.component.ts
* added "prefsFromJSONString" to SzPreferencesComponent. prefs can be initialized from localStorage string directly
* updated docs to reflect current state of methods / repo location
> method to allow web components to load prefs from JSON string

- angular.json
- examples/search-by-id/browserslist
- examples/search-by-id/src/app/app.component.html
- examples/search-by-id/src/app/app.component.scss
- examples/search-by-id/src/app/app.component.ts
- examples/search-by-id/src/app/app.module.ts
- examples/search-by-id/src/app/prefs/prefs-manager.component.html
- examples/search-by-id/src/app/prefs/prefs-manager.component.scss
- examples/search-by-id/src/app/prefs/prefs-manager.component.ts
- examples/search-by-id/src/environments/environment.prod.ts
- examples/search-by-id/src/environments/environment.ts
- examples/search-by-id/src/index.html
- examples/search-by-id/src/main.ts
- examples/search-by-id/src/polyfills.ts
- examples/search-by-id/src/styles.scss
- examples/search-by-id/tsconfig.app.json
- examples/search-by-id/tslint.json
- examples/search-with-prefs/src/app/app.component.html
- package-lock.json
- package.json
- src/lib/sdk.module.ts
- src/lib/services/sz-admin.service.ts
- src/package.json
- src/public_api.ts
- Added **SzAdminService** Class
- Added **search-by-id** example
- Reverted changes to **search-with-prefs**
- Bumped version from 1.1.0 to **1.2.0** for next release
#114 #115
> SDK exported service class to talk to the admin api endpoint

- angular.json
- examples/search-by-id/browserslist
- examples/search-by-id/src/app/app.component.html
- examples/search-by-id/src/app/app.component.scss
- examples/search-by-id/src/app/app.component.ts
- examples/search-by-id/src/app/app.module.ts
- examples/search-by-id/src/app/prefs/prefs-manager.component.html
- examples/search-by-id/src/app/prefs/prefs-manager.component.scss
- examples/search-by-id/src/app/prefs/prefs-manager.component.ts
- examples/search-by-id/src/environments/environment.prod.ts
- examples/search-by-id/src/environments/environment.ts
- examples/search-by-id/src/index.html
- examples/search-by-id/src/main.ts
- examples/search-by-id/src/polyfills.ts
- examples/search-by-id/src/styles.scss
- examples/search-by-id/tsconfig.app.json
- examples/search-by-id/tslint.json
- examples/search-with-prefs/src/app/app.component.html
- package-lock.json
- package.json
> split out get by id example from prefs example

- src/lib/entity/detail/sz-entity-detail-graph/sz-standalone-graph.component.html
- src/lib/entity/detail/sz-entity-detail-graph/sz-standalone-graph.component.scss
- src/lib/entity/detail/sz-entity-detail-graph/sz-standalone-graph.component.ts
- src/lib/search/sz-search/sz-search.component.ts
- src/lib/services/sz-folios.service.ts
added safety checks
addressed hardcoded width expression. #121 
added event emitters:
- SzStandaloneGraphComponent.dataSourcesChange
- SzStandaloneGraphComponent.dataLoaded
> bugfixes. #121

- package-lock.json
- package.json
#142 
dependency updates
security bulletins. we were having some issues updating dependencies that were dependencies of other dependencies. This seems to resolve the issues. Going to have to test it against a <2.0 release version of the api server though.
> #142 dependency updates

- package.json
- src/README.md
- src/lib/common/utils.ts
- src/lib/entity/detail/sz-entity-detail-header/header.component.html
- src/lib/entity/detail/sz-entity-detail-header/header.component.scss
- src/lib/entity/detail/sz-entity-detail-header/header.component.ts
- src/lib/entity/detail/sz-entity-detail.component.ts
- src/lib/entity/entity-utils.ts
- src/lib/search/sz-search/sz-search.component.ts
- src/package.json
- src/public-api.ts
resolves #159 
Adds the "entity id" to the entity detail panel.
> Issue159.awinters.1

- package.json
- src/README.md
- src/lib/common/utils.ts
- src/lib/entity/detail/sz-entity-detail-graph/sz-entity-detail-graph.component.ts
- src/lib/entity/detail/sz-entity-detail-graph/sz-standalone-graph.component.ts
- src/lib/entity/detail/sz-entity-detail-header/header.component.html
- src/lib/entity/detail/sz-entity-detail-header/header.component.scss
- src/lib/entity/detail/sz-entity-detail-header/header.component.ts
- src/lib/entity/detail/sz-entity-detail.component.ts
- src/lib/entity/entity-utils.ts
- src/lib/entity/sz-entity-record-card/sz-entity-record-card-header/sz-entity-record-card-header.component.ts
- src/lib/search/sz-search-result-card/sz-search-result-card-header/sz-search-result-card-header.component.ts
- src/lib/search/sz-search/sz-search.component.ts
- src/package.json
- src/public-api.ts
resolves #156 
Fixes graph reload state condition. (causes graph data displayed to be one cycle behind the currently selected entity Id when bouncing from entity to entity through the detail report)
> Backport 999/APP changes to community artifacts

- package-lock.json
- package.json
- src/package.json
> #170 rest-api-client-ng updated to 2.2.0

- src/lib/search/sz-search/sz-search.component.ts
resolves #196 
needed to add an additional safety check. it was throwing on null.
> #196 add null safety check

- src/lib/entity/detail/sz-entity-details-section/collapsible-card.component.html
- src/lib/entity/detail/sz-entity-details-section/collapsible-card.component.ts
- src/lib/entity/detail/sz-entity-details-section/sz-entity-details-section.component.html
- src/lib/entity/detail/sz-entity-details-section/sz-entity-details-section.component.ts
- src/lib/entity/sz-entity-record-card/sz-entity-record-card-content/sz-entity-record-card-content.component.scss
- src/lib/entity/sz-entity-record-card/sz-entity-record-card-content/sz-entity-record-card-content.component.ts
resolves #211 
To correctly display columns in a record row when other records have data for column, but individual records lacks data that other records have.
layout prettyness.
> Issue211.awinters.1

- package-lock.json
resolves #235
update and verify dependency integrity
pre-release task
> Issue235.awinters.2

- examples/search-in-graph/src/app/app.component.html
- examples/search-with-results-and-details/src/app/app.component.html
- examples/search-with-results-and-details/src/app/app.component.ts
- examples/search-with-results-and-details/src/index.html
- package-lock.json
- package.json
- sdk-components-web/package.json
- src/lib/entity/detail/sz-entity-detail-graph/sz-entity-detail-graph.component.html
- src/lib/entity/detail/sz-entity-detail-graph/sz-entity-detail-graph.component.scss
- src/lib/entity/detail/sz-entity-detail-graph/sz-entity-detail-graph.component.ts
- src/lib/entity/detail/sz-entity-detail-graph/sz-standalone-graph.component.html
- src/lib/entity/detail/sz-entity-detail-graph/sz-standalone-graph.component.scss
- src/lib/entity/detail/sz-entity-detail-graph/sz-standalone-graph.component.ts
- src/lib/entity/detail/sz-entity-detail.component.html
- src/lib/entity/detail/sz-entity-detail.component.ts
- src/lib/scss/_variables.scss
- src/package.json
- src/schematics/ng-add/index.ts
resolves #240 
to add zoom and pan controls to embedded graph
usability
> Issue240.awinters.1

- package-lock.json
resolves #245 
pre-release maintenance task
> Issue245.awinters.3

- package.json
- src/lib/entity/sz-entity-record-card/sz-entity-record-card-content/sz-entity-record-card-content.component.html
- src/lib/entity/sz-entity-record-card/sz-entity-record-card-content/sz-entity-record-card-content.component.scss
- src/lib/scss/theme.scss
- src/lib/why/sz-why-entity.component.ts
- src/package.json
resolves #278 
ux bug introduced with #275 
ui
> why button margin correction and theme values added

- src/lib/why/sz-why-entity.component.ts
resolves #285 
When trying to parse the Why Report data, entities that had NO_MATCH would be missing data points needed to draw out the table.
Why report stability.
> #285 added safety check for no matches

- CHANGELOG.md
- package-lock.json
- package.json
- sdk-components-web/package.json
- src/package.json
- src/schematics/ng-add/index.ts
resolves #297 
update libs to final 3.x compatible public releases
> update libs to final 3.x compatible public releases

- src/lib/graph/sz-relationship-network/sz-relationship-network.component.ts
resolves #319 
graph UI readability/usability impact
graph UI readability/usability
> #319 circleCoord bugfix

- src/lib/graph/sz-graph.component.ts
resolves #321 
bugfix for graph match key token filtering
match key token filtering
> #321 core match key token filtering bug fix

- src/lib/graph/sz-graph-filter.component.ts
- src/lib/graph/sz-graph.component.ts
- src/package.json
resolves #326 
bugfix
graph usability
> #326 bugfix

- CHANGELOG.md
- src/lib/entity/detail/sz-entity-detail-graph/sz-entity-detail-graph.component.ts
- src/lib/entity/detail/sz-entity-detail-graph/sz-standalone-graph.component.html
- src/lib/entity/detail/sz-entity-detail.component.html
- src/lib/entity/detail/sz-entity-detail.component.ts
- src/lib/graph/sz-graph-filter.component.ts
- src/lib/graph/sz-graph.component.ts
- src/lib/graph/sz-relationship-network/sz-relationship-network.component.ts
- src/lib/models/graph.ts
resolves #329 
bugfix
graph filtering bugfix
> #329 graph filtering bugfix

- CHANGELOG.md
- src/lib/graph/sz-graph.component.ts
- src/lib/graph/sz-relationship-network/sz-relationship-network.component.ts
- src/package.json
resolves #343 
for readability
> #343 fix for long match key lines

- src/lib/graph/sz-graph-filter.component.ts
- src/lib/graph/sz-graph.component.ts
resolves #344 
bugfix
graph core node mode filtering
> #344 bugfix

- CHANGELOG.md
- src/lib/entity/detail/sz-entity-detail-graph/sz-standalone-graph.component.ts
- src/lib/graph/sz-graph-filter.component.ts
> Issue348.awinters.2

- package-lock.json
- package.json
- proxy.conf.json
resolves #367
closes #338 
closes #352 
closes #353 
closes #361 
closes #362
dependency updates.
> dependency patches and updates

- package-lock.json
- package.json
- src/lib/common/utils.ts
- src/lib/graph/sz-relationship-network-input/sz-relationship-network-input.component.ts
- src/lib/graph/sz-relationship-network-lookup/sz-relationship-network-lookup.component.ts
- src/lib/graph/sz-relationship-network/sz-relationship-network.component.ts
- src/lib/graph/sz-relationship-path/sz-relationship-path.component.ts
- src/lib/services/sz-search.service.ts
- src/lib/why/sz-why-entities.component.ts
- src/lib/why/sz-why-entity.component.ts
resolves #388 
to update sdk components for the [@senzing/rest-rest-api-client-ng@5.0.0](https://github.com/Senzing/rest-api-client-ng/releases/tag/5.0.0) release
compatibility with the  [senzing-rest-api-specification@3.1.0](https://github.com/Senzing/senzing-rest-api-specification/tree/3.1.0)
> #388 @senzing/rest-api-client-ng@5.0.0 updates

- src/package.json
resolves #388 
forgot to bump up the @senzing/rest-api-client-ng version
> #388 version bump for rest-api-client-ng@5.x.x

- src/lib/graph/sz-relationship-network/sz-relationship-network.component.html
- src/lib/graph/sz-relationship-network/sz-relationship-network.component.ts
resolves #392 
some debugging info snuck through
> #392 cleanup

- src/lib/graph/sz-graph-filter.component.html
- src/lib/graph/sz-graph.component.scss
- src/lib/scss/theme.scss
- src/subrepo.ng-package.json
- src/subrepo.tsconfig.lib.json
- tsconfig.subrepo.json
there were several build tooling changes (mostly in the `*.tsconfig.json` files that were needed in order to perform a build from a parent repo project that had this module checked out as a subrepo in order to build this project. 
In order to keep the main branch updated with subrepo layout compilation. I've already performed a **_non-submodule_** package build/publish testing lifecyle so none of these changes should impact the normal library build process.
build tooling compatibility
> merge in changes made for app to compile to main

- examples/search-in-graph/src/app/app.component.ts
- src/lib/graph/sz-graph-filter.component.scss
- src/lib/graph/sz-relationship-network/sz-relationship-network.component.ts
- src/lib/scss/graph.scss
- src/lib/scss/theme.scss
resolves #433 
when the whole name char count was less than the word break tolerance it would initialize with the whole name as the first line. the result would appear as though there are two(or more) lines that are identical
bugfix
> #433 bugfix

- src/lib/entity/detail/sz-entity-detail-graph/sz-standalone-graph.component.html
- src/lib/graph/sz-graph-filter.component.html
- src/lib/graph/sz-graph.component.ts
- src/package.json
resolves #432 
selection scope state was incorrect at different component levels
"Directly Related" graph match key tokens now reflects accurate scope
> #432 selection scope bugfix

- CHANGELOG.md
- src/lib/entity/detail/sz-entity-detail.component.ts
- src/lib/entity/detail/sz-entity-details-section/sz-entity-details-section.component.ts
- src/lib/entity/sz-entity-record-card/sz-entity-record-card-content/sz-entity-record-card-content.component.ts
- src/lib/why/sz-why-entities-dialog.component.html
- src/lib/why/sz-why-entities.component.ts
- src/lib/why/sz-why-entity.component.ts
> #436 add entity name to why/why not header

- package-lock.json
resolves #nnn
fixes a dep issue marked critical
> sec update

- src/lib/entity/sz-entity-record-card/sz-entity-record-card-content/sz-entity-record-card-content.component.html
resolves APP-790
why buttons in records embedded in detail view were not working.
functionality
> fix for why button embedded in detail viewer

- CHANGELOG.md
- package-lock.json
- package.json
resolves #471 
going from alpha to beta tag
> @senzing/rest-api-client-ng updated to @6.0.0-beta.1

- package-lock.json
- package.json
resolves #473 
changing dependency from @beta to @final
stability/maintanability
> update @senzing/rest-api-client-ng to @6.0.0

- src/lib/entity/detail/sz-entity-detail-graph/sz-standalone-graph.component.ts
- src/lib/graph/sz-relationship-network/sz-relationship-network.component.ts
resolves #493 
to fix some graph bugs
> #493 forward merge of team_sprint60 changes

- examples/search-with-results-and-details/src/app/app.component.html
- examples/search-with-results-and-details/src/app/app.component.ts
- src/lib/how/sz-how-entity.component.ts
- src/lib/services/sz-how-ui.service.ts
resolves #516 
how report would only load data for the first entity requested. subsequent requests were not clearing out cached results.
bugfix
> #516 clear out cached how results on entity id change

- src/lib/how/cards/sz-how-card-base.component.ts
- src/lib/how/cards/sz-how-step-card.component.html
resolves #547 
@jbutcher21 requested that the virtual entity with less records always be on the left to match the logic in G2Explorer.
behavioral consistency
> put smaller virtual entity on left

- src/lib/how/cards/sz-how-card-base.component.ts
- src/lib/how/sz-how-nav.component.ts
resolves #547 
both sides of the comparison datatable were only showing the "candidate" feature value.
bugfix
> #547 bugfix

- src/lib/how/sz-how-nav.component.ts
resolves #555
more accurate how component search results
> Improved Free Text search in how navigation

- src/lib/how/sz-how-step-stack.component.scss
- src/lib/how/sz-how-virtual-entity-dialog.component.scss
- src/lib/how/sz-how-virtual-entity-dialog.component.ts
- src/lib/scss/theme.scss
- src/lib/scss/themes/senzing.css
- src/lib/services/sz-how-ui.service.ts
> #567 how: virtual entity window fixes

- src/lib/models/data-why.ts
- src/lib/scss/why.scss
- src/lib/services/sz-how-ui.service.ts
- src/lib/why/sz-why-entities.component.html
- src/lib/why/sz-why-entities.component.scss
- src/lib/why/sz-why-entities.component.ts
- src/lib/why/sz-why-entity.component.html
- src/lib/why/sz-why-entity.component.scss
- src/lib/why/sz-why-entity.component.ts
- src/lib/why/sz-why-report-base.component.ts
resolves #558 
the "Why" report had several inconsistencies between it and the "Why N0T" report and the versions found in the G2Explorer tools
> fixes for "Why" report

- src/lib/how/cards/sz-how-card-base.component.scss
- src/lib/how/cards/sz-how-card-base.component.ts
- src/lib/how/cards/sz-how-final-entity-card.component.ts
- src/lib/how/cards/sz-how-singleton-card.component.html
- src/lib/how/cards/sz-how-singleton-card.component.ts
- src/lib/how/cards/sz-how-step-card.component.html
- src/lib/how/cards/sz-how-step-card.component.ts
- src/lib/how/sz-how-entity.component.ts
- src/lib/how/sz-how-step-node.component.html
- src/lib/how/sz-how-step-node.component.ts
- src/lib/models/data-how.ts
- src/lib/models/data-why.ts
- src/lib/scss/why.scss
- src/lib/sdk.module.ts
- src/lib/services/sz-how-ui.service.ts
- src/lib/why/sz-why-entities.component.html
- src/lib/why/sz-why-entities.component.scss
- src/lib/why/sz-why-entities.component.ts
- src/lib/why/sz-why-entity.component.html
- src/lib/why/sz-why-entity.component.scss
- src/lib/why/sz-why-entity.component.ts
- src/lib/why/sz-why-report-base.component.ts
- src/public-api.ts
resolves a bad/incorrect nesting/parsing issue with the primary data-transform.
- The nesting and what _was/was not_ an interim step was being parsed incorrectly. 
- Unresolved entities with multiple final states could not be displayed correctly.
- display/nesting of interim and stack members is now congruent with the g2Explorer display.
- simplified data-transform
> How data transform node traversal refactoring

- src/lib/how/cards/sz-how-card-base.component.ts
- src/lib/how/cards/sz-how-step-card.component.html
- src/lib/how/sz-how-entity.component.ts
- src/lib/how/sz-how-step-stack.component.ts
- src/lib/services/sz-how-ui.service.ts
resolves #571 
functionality was temporarily disabled until the cause of issue could be addressed.
pin/unpin stack(s) functionality added back in.
> How: fix pin/unpin stack(s) feature

- .gitignore
- package-lock.json
- src/lib/why/sz-why-entities.component.ts
resolves #583 
pre-release task
> Issue583.awinters.1

- src/lib/entity/detail/sz-entity-detail-graph/sz-standalone-graph.component.ts
- src/lib/entity/detail/sz-entity-detail.component.ts
- src/lib/search/sz-search-results/sz-search-results.component.ts
resolves #588 
why not modal could not scroll properly from graph context
> #588 css bugfix

- src/lib/why/sz-why-entities.component.ts
resolves #592 
the logic for what names have little tree's that point to names not in the columns entity needed to be rewritten.
- names/addresses/other that have matches/scores that point to values in the other column(entity) in why not report should show scores and tree/arrow pointer.
- values in cells should be ordered by score.
- values should not show duplicates in same cell.
> #592 fixes for why not value pointers, line value ordering by scores, duplicates.

- README.md
resolves #675 
urls were out of date
documentation
> updated new doc org paths

- .github/workflows/npm-build.yaml
- .gitignore
- package-lock.json
- package.json
- src/README.md
- src/package.json
resolves #669 
pre-release maintenance task
> dependencies updated and node version to 18.x

- src/lib/graph/sz-relationship-network/sz-relationship-network.component.ts
graph tooltip not being cleaned up properly
graph component would add a node to the dom but never remove it.
> fix for graph tooltip not being properly garbage collected
